# 04-函数

> 介绍函数, 参数, 闭包, 错误的捕获与处理.

---

## 声明函数

声明函数时, 需要给出 `函数名` (可选), `参量` (可选), `函数体`.

```js
// 定义一个计算平均值的函数
function average(x, y) {
    return (x + y) / 2;
}

// 调用这个函数
let result = average(6, 7);
```

> ⚠️ 声明函数时, 如果不提供函数名, 则定义了一个匿名函数.

---

## 把函数作为参数

可以把函数作为参数传递给另一个函数. 例如:

```js
// 定义一个返回立方数的函数
function cube(x) {
    return x ** 3;
}

// 把函数 cube 作为数组的 map 方法的参数
[1, 2, 3, 4].map(cube); // [ 1, 8, 27, 64 ]

// 还可以直接传给 map 方法一个匿名函数
[1, 2, 3, 4].map(function (x) { return x ** 3; });

// 另一个传入匿名函数的例子
[1, 2, 3, 4].filter(function (x) { return x > 2 ? true : false; }); // [ 3, 4 ]
```

---

## 闭包

**闭包 (closure) 就是一个带引用环境 (referencing environment) 的函数**.

### 闭包图解

我们来看这个例子:

```js
let justAVar = "我是全局变量";      // 定义一个全局变量

function whoAreYou() {
    let justAVar = "我是局部变量";  // 这是和外部变量同名的局部变量

    function inner() {      // inner 是在函数 whoAreYou 内部定义的函数, 即内嵌函数
        return justAVar;    // 内层函数里使用到外部变量
    }

    return inner;   // 返回一个函数. 没错, 函数也可以作为返回值
}

let innerFunction = whoAreYou();    // 每次调用 whoAreYou, 会返回一个函数
let result = innerFunction();       // 调用返回的函数 (即闭包)
console.log(result);                // 结果是 "我是局部变量"
```

当调用函数 `whoAreYou` 时, 返回的就是 **闭包**.

![闭包图解](../../_assets/_images/closure.svg ':size=800')

然后调用闭包 `innerFunction`. 当闭包需要用到某个变量时, 会首先在自己的引用环境里查找. 如果在引用环境里找不到需要的变量, 就向上一层继续查找, 直至全局变量. 如果连全局变量都没有, 则返回 `undefined`.

> ⚠️ 函数的形参相当于局部变量, 所以也会在闭包的引用环境中. 在 JavaScript 中, **只有函数会引入新的作用域 (scope)**.

典型情况下, 一个函数会在函数体里定义自己的局部变量 (包括形参). 对于函数体里没有定义, 但使用到的变量, 称为自由变量 (free variables). 例如上例中的变量 `justAVar` 对于函数 `inner` 就是自由变量. 自由是指在函数体里该变量没有绑定到任何值. 如果有一个环境来储存这些自由变量, 就说封闭了这个函数. 函数和其环境一起, 被称为闭包.

![闭包图解2](../../_assets/_images/closure2.svg ':size=600')

将一个 **具有自由变量的函数** 与一个 **为所有这些自由变量提供变量绑定的环境** 结合起来, 就产生了一个 **闭包**. 

### 返回函数创建闭包

对于计数器, 需要一个变量 `count` 来存储每次计数后的值. 如果把 `count` 声明为全局变量, 就会导致多个计数器去操作同一个计数变量, 从而导致冲突. 另外当我们和别人合作时, 别人有可能也声明了一个叫 `count` 的全局变量.

为了避免冲突, 最好是用闭包来实现计数器.

```js
// 生成计数器 counter 的函数
function makeCounter() {
    let count = 0;          // 局部变量 count 对于函数 counter 是自由变量

    function counter() {    // 创建 counter 函数, 实现 count 变量的自增
        count++;
        return count;
    }

    return counter;         // 这里返回的函数就是闭包
}

// 生成两个 counter, 他们各自有自己的引用环境, 互不干扰
let doCount1 = makeCounter();
let doCount2 = makeCounter();
console.log(doCount1());    // 1
console.log(doCount1());    // 2
console.log(doCount2());    // 1
```

### 把函数作为参数创建闭包

每当引用具有自由变量的函数, 且该函数在创建他的上下文之外执行, 就创建了一个闭包. 因此, 除了通过返回一个函数来创建闭包, 还可以通过把函数作为参数来创建闭包.

```js
// 这是一个定时弹窗显示 doneMessage 的函数
function makeTimer(doneMessage, n) {
    // 形参 doneMessage 相当于定义在函数 makeTimer 作用域的局部变量,
    // 因此, doneMessage 对于下面的匿名函数来说就是自由变量.
    // setTimeout 接收的是闭包 (匿名函数的引用 + 环境)
    setTimeout(function () {
        alert(doneMessage);
    }, n);
}

// 两者弹出的消息内容互不干扰
makeTimer("Cookies 1 are done!", 1000);
makeTimer("Cookies 2 are done!", 2000);
```

### 事件处理器创建闭包

本质也是把函数作为参数来创建闭包.

<p class="codepen" data-height="300" data-default-tab="html,result" data-slug-hash="XWePvxX" data-editable="true" data-user="luckyzhz" style="height: 300px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;">
  <span>See the Pen <a href="https://codepen.io/luckyzhz/pen/XWePvxX">
  用事件处理器创建闭包</a> by luckyzhz (<a href="https://codepen.io/luckyzhz">@luckyzhz</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://cpwebassets.codepen.io/assets/embed/ei.js"></script>

---

## 检测参数类型

JavaScript 是动态语言, 所以给函数传参时可以传入任意类型的数据. 为了使程序运行更稳定, 可以在函数体里检测传入的数据的类型. 下表是常见的类型与对应的检测语句:

| 类型      | 检测语句                    |
| --------- | --------------------------- |
| 字符串    | `typeof x === 'string';`    |
| 正则式    | `x instanceof RegExp;`      |
| 数字      | `typeof x === 'number';`    |
| 数组      | `Array.isArray(x);`         |
| 函数      | `typeof x === 'function';`  |
| undefined | `typeof x === 'undefined';` |

```js
// 这是一个求平均数的函数, 可以接受数字或一维数组
function average(x, y) {
    let sum = 0;
    let n = 0;

    if (Array.isArray(x)) {
        for (const value of x) {
            sum += value;
            n++;
        }
    } else {
        sum += x;
        n++;
    }

    if (Array.isArray(y)) {
        for (const value of y) {
            sum += value;
            n++;
        }
    } else {
        sum += y;
        n++;
    }

    return n === 0 ? 0 : sum / n;
}

// 可以传入数字或数组
average(1, 2);              // 1.5
average([1, 2, 3], 4);      // 2.5
average(1, [2, 3, 4]);      // 2.5
average([1, 2], [3, 4, 5]); // 3

// 提供的参数如果多于两个, 多余的参数会被忽略;
// 如果少于两个, 缺少的参数值是 `undefined`
average(3, 4, 5);   // 3.5 (多余的参数 5 被忽略)
average(3);         // NaN
```

---

## 参数默认值

声明函数时, 可以赋给参数默认值. 当调用函数而没有提供对应参数时, 就会使用参数默认值. 给参数设置默认值, 可以避免值为 `undefined`.

```js
// 参数 x 的默认值是 0, y 的默认值是 x
function average(x = 0, y = x) {
    return (x + y) / 2;
}

average(3); // 3, 即 average(3, 3);
average();  // 0, 即 average(0, 0);
```

---

## 剩余参数和展开运算符

剩余参数和展开运算符的符号都是 `...`. 剩余参数在定义函数时使用. 展开运算符在函数调用, 以及其他需要展开数组的场合使用.

### 剩余参数

定义参数时, 如果不确定参数个数, 可以使用剩余参数的写法.

```js
// ...others 表示多余的参数会以数组的形式存放在变量 others 中;
// 如果没有多余参数, 则 others 是空数组
function average(first = 0, ...others) {
    let sum = first;
    for (const value of others) {
        sum += value;
    }
    return sum / (1 + others.length);
}

average(3);             // 3
average();              // 0
// first = 1, others = [7, 2, 9]
average(1, 7, 2, 9);    // 4.75
```

### 展开运算符

有些函数接受多个参数, 但不接受数组, 这时可以用展开运算符把数组展开.

```js
// Math.max 可以求得传入参数的最大值
Math.max(3, 1, 4, 1, 5);    // 5

let numbers = [1, 7, 2, 9];

// 数组直接传入, 会作为一个参数
Math.max(numbers);          // NaN

// 使用展开运算符, 一个元素就是一个参数
Math.max(...numbers);       // 9, 即 Math.max(1, 7, 2, 9);
```

展开运算符还可以用在其他需要展开数组的场合.

```js
let numbers = [1, 7, 2, 9];

// 把 numbers 展开后作为新数组的元素
// 结果是 [ 1, 2, 3, 1, 7, 2, 9 ]
let moreNumbers = [1, 2, 3, ...numbers];
```

字符串也可以展开.

```js
let greeting = "Hello 😀";

// 结果是 [ "H", "e", "l", "l", "o", " ", "😀" ]
let characters = [...greeting];
```

## 错误

可以自定义并抛出错误, 以处理一些意外情况.

### 抛出错误

当一个函数无法处理某些情况时, 最好是抛出设计好的错误 (error) , 以返回有用的信息. 抛出错误使用 `throw` 语句. 抛出的可以是任何类型的数据, 但惯用 error object. 当 `throw` 语句被执行时, 函数就终止了.

```js
let reason = `Element ${elem} not found`;

// 用 Error 函数生成 error object
// error object 有两个属性, `name`, `message`
throw Error(reason);
```

### 处理错误

使用 `try...catch` 语句来捕获处理错误. 错误被捕获后, 程序就可以继续运行, 而不会终止.

```js
try {
    // Do work
    . . .
} catch (e) {   // 抛出的异常存放在变量 e 中
    // Handle error
    . . .
}
```

`try...catch` 语句还可以有 `finally` 语句块. 不论是否抛出错误, 都会执行 `finally` 语句块.

```js
// catch 和 finally 语句块都是可省略的
try {
    . . .
} catch (e) {
    . . .
} finally {
    . . .
}
```

`finally` 语句块通常用来释放 `try` 语句块获得的资源 (如操作文件或连接数据库).



---

?> {docsify-updated}